name: Laravel CI

on:
  push:
    branches:
      - main
    conditions: ${{ github.event_number % 3 == 0 }}

jobs:
  laravel-test:
    name: Run Laravel tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install Composer dependencies
        run: composer install --prefer-dist --verbose --no-ansi --no-interaction --no-scripts

      - name: Copy environment file
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate
